name: Flutter CI/CD

on:
  push:
    branches: [main]

jobs:
  build_and_test:  # Nom du job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Flutter
        use: subosito/flutter-actionv@2
        with:
          flutter-version: '3.29.3'
          chanel: 'stable'

      - name: Get dependencies
        run: flutter pub get


      - name: Lancer les testes
        run: flutter test


      - name: Build pour le web
        run: flutter build web --release
